### ISSUE TITLE
Logs from multiple jobs are getting combined into last build allure report

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-teamcity-plugin#23]
Recently i've noticed strange behaviour of allure reports in Team City : 
1. I run couple of jobs for same project
2. Let's say they all fail
3. When i open last run job and look into Allure report, i see failures from previous jobs as well. 

I have next settings for allure feature in build configuration : 

Results Directories: **/allure-results
Report Version: 1.4.0
Generate: For all builds

Do i miss something on reports generation step or should i specify Results Directories in a different way ? 

Thanks.

**Comment by vania-pooh** [comment]
@azakordonets this is probably because Teamcity for some reason is not cleaning your workspace before each build. You need to ensure that allure-results directory contains XML files and attachments for current run only. From Allure point of view there's no difference between XML files from the first build and the second one so Teamcity generates you a merged report using both XML file collections and both attachment collections.

**Comment by azakordonets** [comment]
Yeah, looks like you're right - i will need to clean **/allure-reports folder before each run. Thanks for quick response.
